#!/bin/bash

cd $HOME

echo -e "====Installing ASDF====\n"
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.1

echo -e "====Making Github Directory====\n"
mkdir $HOME/github

echo -e "==== Making Bitbucket Directory ====\n"
mkdir $HOME/bitbucket

echo -e "==== Cloning Github Repos ====\n"
cd $HOME/github && git clone https://github.com/wookiee89/azure-resource-graph.git
cd $HOME/github && git clone https://github.com/wookiee89/nodejs-helloworld.git

echo -e "==== Installing Az CLI ====\n"
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

